// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXAsXJtoDSe7KkgrvjUaIAPR1aElVznU',
    appId: '1:998704769759:web:6714352deb09887575176a',
    messagingSenderId: '998704769759',
    projectId: 'studybuddyapp-93539',
    authDomain: 'studybuddyapp-93539.firebaseapp.com',
    databaseURL: 'https://studybuddyapp-93539-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddyapp-93539.appspot.com',
    measurementId: 'G-7J67S05RQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABa1xYTBLJR2fV-WLJfNGISuM-VY-ag9k',
    appId: '1:998704769759:android:98bcacfecec1357f75176a',
    messagingSenderId: '998704769759',
    projectId: 'studybuddyapp-93539',
    databaseURL: 'https://studybuddyapp-93539-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddyapp-93539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30nYhWNQBpWYg9XbW71qm2uhZe3CHTa4',
    appId: '1:998704769759:ios:47d9c71636d59ec675176a',
    messagingSenderId: '998704769759',
    projectId: 'studybuddyapp-93539',
    databaseURL: 'https://studybuddyapp-93539-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddyapp-93539.appspot.com',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30nYhWNQBpWYg9XbW71qm2uhZe3CHTa4',
    appId: '1:998704769759:ios:71728fc1dc696e7775176a',
    messagingSenderId: '998704769759',
    projectId: 'studybuddyapp-93539',
    databaseURL: 'https://studybuddyapp-93539-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddyapp-93539.appspot.com',
    iosBundleId: 'com.example.studybuddy.RunnerTests',
  );
}
